### PR TITLE
Custom HD44780 Codecs (A00/A02)

### PR DESCRIPTION
**Pull request by dbrgn**
Work in progress. Solves #15.

I want to fully integrate these codecs into the library.

7 characters in the A00 table still remain unclear to me (0xE7, 0xE9, 0xEA, 0xF0, 0xF1, 0xF8, 0xF9).

### CODE REVIEW

**Comment by dbrgn** [comment]
How this should work: When initializing the CharLCD class, the user should specify the character table.

The write methode should always be used with unicode objects. These unicode strings are then automatically converted to the correct encoding.

**Comment by rfarley3** [comment]
I wrote a quick char map for the a00 variant, only to find your much more robust version based on the codec package. I may have some data points that can help you. (and would be willing to help after you/we/others decide what values/chars map as what.)

* 0xe7, ea, f0, f1, f9: from the datasheet, these look like g, j, p, q, y (respectively) such that their tails are in the bottom 2 dot rows. I haven't verified this on my LCD to see if they are ignored or displayed raised on 5x8 dot panels. I have not found the UTF codes for bottom aligned/raised g, j, p, q, y to use in 0x67, 6a, 70, 79. But I don't know how much I care about accuracy here since encoding g as 0xe7 is unintuitive.
* 0xe9 is superscript-neg-1, which I can't find as a single width combo-char, so I use \u207b\u00b9.
* 0xf8, it is x-bar \u0078\u0304.

Other UTF values that should perhaps be encode-able:
* 0xeb alternative could be superscript-x \u02e3.
* 0xed alternative could be the Pounds Sterling symbol \u00a3.
* 0xf6 alternative could be a variant of cap-sigma \u2211.
* 0xff alternative could be a taller block \u2588.

Somethings I noticed about the Japanese mappings you currently have:
* [0xa0](https://github.com/dbrgn/RPLCD/blob/codec/RPLCD/codecs/hd44780_a00.py#L178)
Given how this is just before the kana characters, I suspect that the original mapping is actually intended to represent the Japanese space character \u3000.
* [0xde](https://github.com/dbrgn/RPLCD/blob/codec/RPLCD/codecs/hd44780_a00.py#L243)
This is technically correct for decoding hitachi bytes to UTF, the character rarely doesn't modify the previous character. But I don't think this is what we want for encoding. It is one of those UTF chars that modify the previous char, such that they both only take up a single character width. On the LCD, they can't share a character and should each have its own char. The stand-alone version is \u309b. I do not know if there is a 1/2 width version of this character. My vote would be for consistency to mimic what is on the LCD, and I would decode 0xde to \u309b. But allow both \u309b and \uffdf to encode to 0xde.
* [0xdf](https://github.com/dbrgn/RPLCD/blob/codec/RPLCD/codecs/hd44780_a00.py#L244)
Same as L243, but for \u309c. Additionally, there is very very visually similar \u00b0.

**Comment by dbrgn** [comment]
@rfarley3 great, thanks for your input :)

I'm very busy this week, but I hope I find time to finish this issue and release a new version soon. Hopefully next week. I'll take a closer look at the mentioned things then!

**Comment by rfarley3** [comment]
I took a picture of the questionable bytes on my hitachi a00:
[Questionable Bytes](https://postimg.org/image/tmi8fggmp/)

Here's the order of the bytes from the image:
```
    odd_chars = [
        b'\x67\x6a\x70\x71\x79',
        b'\xe7\xea\xf0\xf1\xf9',
        b'\xe9\xf8',
        b'\xeb\xed\xf6\xff']
    lcd.message(odd_chars, raw=True)  # function that wraps your lcd.write() st each list element is a row of raw bytes to write from the entry point
```

**Comment by rfarley3** [comment]
Also, not sure if this is helpful, but I finally got around to pushing the code where I did that codec hack: https://github.com/rfarley3/lcd-restful/blob/master/lcd_restful/codec.py

**Comment by dbrgn** [comment]
Finally some tests with a mocked LCD :sparkles:

**Comment by dbrgn** [comment]
Finally some tests with a mocked LCD :sparkles:

**Comment by dbrgn** [comment]
I took a closer look at the codec. I think it's not the right tool for the task.

The problem is that character maps must be bijective / invertible, meaning that `'x'.encode(foo).decode(foo)` yields `'x'` again, no matter what codec was used.

In our case, we don't actually need the decoding step, since the bytes are only relevant for the LCD. We want a surjective function, where various inputs (e.g. multiple versions of a unicode right arrow) can be mapped to the same output.

Therefore I'll rewrite the character map to a simple mapping dictionary that will be used internally by the `CharLCD` class.

**Comment by dbrgn** [comment]
@rfarley3 thanks a lot for your research and suggestions, that surely saved me some time!

> 0xe7, ea, f0, f1, f9: from the datasheet, these look like g, j, p, q, y (respectively) such that their tails are in the bottom 2 dot rows. I haven't verified this on my LCD to see if they are ignored or displayed raised on 5x8 dot panels. I have not found the UTF codes for bottom aligned/raised g, j, p, q, y to use in 0x67, 6a, 70, 79. But I don't know how much I care about accuracy here since encoding g as 0xe7 is unintuitive.

Yes, looks like the A00 ROM contains some full-height (10 pixel) characters. I don't own any LCD with 5x10 pixel chars, so let's simply ignore those :) People that want them should probably work with `unichr()` since there are probably no unicode codepoints defined for those characters.

> 0xe9 is superscript-neg-1, which I can't find as a single width combo-char, so I use \u207b\u00b9.
> 0xf8, it is x-bar \u0078\u0304.

Using a custom function instead of a codec means that we can support patterns like that :)

> 0xeb alternative could be superscript-x \u02e3.
> 0xed alternative could be the Pounds Sterling symbol \u00a3.
> 0xf6 alternative could be a variant of cap-sigma \u2211.
> 0xff alternative could be a taller block \u2588.
> 0xa0 Given how this is just before the kana characters, I suspect that the original mapping is actually intended to represent the Japanese space character \u3000.

Great suggestions, thanks!

> 0xde This is technically correct for decoding hitachi bytes to UTF, the character rarely doesn't modify the previous character. But I don't think this is what we want for encoding. It is one of those UTF chars that modify the previous char, such that they both only take up a single character width. On the LCD, they can't share a character and should each have its own char. The stand-alone version is \u309b. I do not know if there is a 1/2 width version of this character. My vote would be for consistency to mimic what is on the LCD, and I would decode 0xde to \u309b. But allow both \u309b and \uffdf to encode to 0xde.

Since we're dropping decoding alltogether, I'll simply add both versions to the encoder.

> 0xdf Same as L243, but for \u309c. Additionally, there is very very visually similar \u00b0.

Good point, added all three versions.

**Comment by dbrgn** [comment]
New implementation for A00 is done, A02 still needs to be done. Hopefully tomorrow :)

**Comment by dbrgn** [comment]
Added some more aliases:

- Various heart shapes
- Ohm / Omega
- Sigma / Sum
- Various dashes
- Space and no-break space

**Comment by dbrgn** [comment]
Tests pass and docs are updated. I'll test this on an actuall Raspberry Pi tomorrow, but I think the branch is now ready to merge.

**Pull request merged**
