### PR TITLE
Add test configuration for 40x2 display

### PR DESCRIPTION
**Pull request by paulenuta**
Add test configuration for 40x2 display

Tested confirmed with 40x2 display (RAYSTAR - RC4002A-BIW-JSX) and i2c MCP23008 (Adafruit backpack custom made equivalent). 
[./test_40x2.py i2c MCP23008 0x20 A00]

Do you want me to test also on GPIO?

### CODE REVIEW

**Comment by dbrgn** [comment]
Hi @paulenuta, thanks for your contribution!

I think with a third test script, maintenance is getting complicated. The better approach would probably to make the LCD configuration (rows, cols) configurable as command line parameters (similar to the way it's done in `show_charmap.py`), and to add some `if`s to the test output.

@paulenuta would you like to do that? You could start with the 16x2 example, add `rows` and `cols` parameters and add `if`s everywhere where you need behavior different from the 16x2 LCD.

**Comment by paulenuta** [comment]
Hi Danilo,

I could do that, as you suggested I will start combining the 2 rows scripts.

In the final you want to have one script for `16x2`, `40x2` and `20x4`? If this is the case do you have some "must show" tests in this scripts, as `20x4` has more differences the the 2 rows display.
On the other hand I think `show_charmap.py` has some problems on `40x2` displaying first page reverse.
image
What do you think?

Paul

**Comment by dbrgn** [comment]
Yes, ideally we have 1 script for all of them, but initially just combining the 16x2 and 40x2 are enough.

> On the other hand I think show_charmap.py has some problems on 40x2 displaying first page reverse.

Is it possible that the memory layout of the 40x2 display is done in a way that characters are first written to the lower line, then to the upper line?

**Comment by paulenuta** [comment]
> Is it possible that the memory layout of the 40x2 display is done in a way that characters are first written to the lower line, then to the upper line?

This is what you meant?
image

**Comment by dbrgn** [comment]
Yes. Or in other words, if you run `lcd.clear()` and then write some characters, are they on the first or on the second line?

**Comment by paulenuta** [comment]
Yes, test_40x2.py show right and I also test your [scrolling text](https://blog.dbrgn.ch/2014/4/20/scrolling-text-with-rplcd/) example.

**Comment by dbrgn** [comment]
In that case the `show_charmap.py` should work properly. Do you use current master, or an older version?

**Comment by paulenuta** [comment]
It is current master from this morning manually installed `python setup.py install.`.

**Comment by paulenuta** [comment]
I have install latest master from 15-05-2017 and `show_charmap.py` is working fine on 40x2 LCD.

**Comment by GoranLundberg** [comment]
Wait a little with this. I'm doing some changes to the tests as part of the MCP23017 support. Will probably do a pull request today. We might be able to combine the changes.

**Comment by paulenuta** [comment]
I suppose there is no need for this any more.

**Comment by GoranLundberg** [comment]
Yes, there is! Please add it when the new test system is merged into master.

**Comment by paulenuta** [comment]
Well, you now moving test_##x# to /lcdtests and already intercept cols/rows configuration to choose testsuite which is different from my pr goal to get one test for all combination as said by

> dgrgn: I think with a third test script, maintenance is getting complicated. The better approach would probably to make the LCD configuration (rows, cols) configurable as command line parameters (similar to the way it's done in show_charmap.py), and to add some ifs to the test output.

Anyway, my opinion regarding test (as example of usage) is that it need to be directly accessed by the end user (they are what & how can do of the library)  when it go for test/examples and [`elif test == 'testsuite':`](https://github.com/GoranLundberg/RPLCD/blob/master/lcdtest.py#L196) kind hide from user what really happens.  This, of course does not apply to `show_charmap` or similar "display feature" test.

Paul

**Pull request closed without merging**
