### PR TITLE
Check invalid cursor position only when auto_linebreaks enabled

### PR DESCRIPTION
**Pull request by 007hacky007**
Fixes issue #93

### CODE REVIEW

**Comment by dbrgn** [comment]
Sorry for the late reply! The fix looks good to me at first glance, but I'll try to set up a Raspi to test it before merging.

**Comment by 007hacky007** [comment]
Any update on this? 
Just installed RPLCD via pip after raspbian update and I had to manually patch lcd.py to get it working.

**Comment by dbrgn** [comment]
Hi, I never found the time to test this properly, but I'll just merge it, and people will need to let me know if something breaks 😉 Thanks!

**Comment by dbrgn** [comment]
Release 1.3.1 with this fix is out.

**Comment by 007hacky007** [comment]
Great! Thank you.

**Pull request merged**
